# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171122_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(),
        ),
    ]
